services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - compose.env
    # tty: true
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8000/health"
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    env_file:
     - vite.env
    command: npm run dev
    

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 3

