version: "3.6"

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    env_file:
      - docker-compose.env

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    command: npm run dev
    

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

