version: 1
disable_existing_loggers: false
formatters:
  default:
    (): logging.Formatter
    fmt: "%(asctime)s %(levelname)s %(message)s"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
root:
  handlers: ["default"]
  level: INFO
