apiVersion: v1
data:
  ALGO: HS256
  ALLOWED_IP_ADDRESSES: '["192.168.1.1", "172.20.0.1"]'
  DB_URL: postgresql://postgres:postgres@db/postgres
  JWT_SECRET_KEY: somesecretiwillmake
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: fastapi-docker-compose-env
  name: docker-compose-env
