services:

  app:
    build:
      dockerfile: Dockerfile
    container_name: qftb
    volumes:
      - "..:/workspace"
    env_file:
      - ../compose.env
    tty: true

  db:
    image: 'postgres:latest'
    container_name: postgres-db
    restart: always
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 3
